<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><u><strong>Mega Live---- Terms and Conditions</strong></u></em></span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><a name="_GoBack"></a> <span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">By creating a MegaLive account, whether using a smartphone, desktop PC, users agree to comply with terms of use, cookie policy, privacy policy, community guidelines, and safety tips. If users do not abide by the terms of the agreement, then please do not proceed with availing of the service.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Eligibility requirement:</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Before using our app, users are supposed to register an account. To create a new account, one should&mdash;</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Complete eighteen years of age</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Must be legally allowed to use the app abiding by the laws of your country. Users do have the option to create an account manually</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Shortly, users will be able to register an account with the help of Facebook and other social media giants.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Synchronizing with Facebook implies authorizing us to gain access to your profile information, location, home address, and relationship status.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">For further clarifications regarding methods to use it, kindly go through our privacy policy</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We lay special emphasis on inclusivity; therefore, we do not encourage users to take advantage of another individual's account without their consent. Users do have the option to terminate their account by clicking the settings button, log in to the account and pick 'Delete account link'. Once the process is complete, adequate time is required for the contents to be deleted from the app. </span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Here at MegaLive, a backup option is available wherein profile information could be restored if the users wish to retrieve back their account. However, it could be done within thirty days from the day of deactivation. If the users have deleted their account and attempt to create a fresh one amidst this time using the same address, the internal team will help in reactivating the account on behalf of users.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We, the team of MegaLive do have the sole right to suspend an account and leverage technological means to block the IP address at any point of time without notice.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Ways of signing in to your account:--</strong></em></span></span></span><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">To use the MegaLive app, there are several ways to log in such as social media platforms Facebook. Users have the sole responsibility to preserve the confidentiality of login credentials that are used to sign up for the MegaLive app.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">If you feel any unauthorized access of third parties, please do not hesitate to approach the internal team of MegaLive.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Modifications of Service:----</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">MegaLive is frequently engaged in improving the service and creating extra functionality to enhance user engagement. It implies that we include additional features.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Safe and secure:---</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Here at MegaLive, we would make sure that both parties are interacting and exchanging information with their mutual consent. Under any circumstances, we are not responsible for any misconduct by the members. Users should accept to take preventive measures during interactions with fellow members, especially when they are planning to meet in person.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Not subject to transfer:---</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The members are not permitted to rent, pledge or lend any rights to third parties without the written consent of Mega live. He/she does have the right to make use of plugins in websites that are owned personally by a user. An individual could use plugins in multiple websites unless it is under their ownership.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Termination notice:---</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Mega live have the right to terminate the account of members if the users do not abide by the rules and regulations of Mega live.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Refunds:---</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We, the team of MegaLive request our esteemed members to take a quick look at our features along with a demo to ensure that the software is suited for them. Make sure there are no variations to that of the previous one.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We would make sure that adequate support and guidance to our users concerning any sorts of technical glitches in the plugin. Each issue will be rectified at the earliest by some of our experienced technicians.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We are also not reluctant to pay the full amount which is claimed within ten days</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Apart from that, users must agree to go through and follow the safety tips of MegaLive. Members agree that he/she will not reveal their financial information or deliver money to other members. Users are solely responsible for their interactions with members and Mega live does not carry out a comprehensive criminal background check on their registered members</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Restrictions imposed on certain contents:</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Contents, which appear to be offensive, harass, abusive, embarrass or humiliate another person.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Obscene, violent, and pornographic contents which could offend human integrity</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Strict actions are taken when a user makes derogatory remarks or promotion of sexism and racism.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Spreading or exchange of junk mails will not be encouraged.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Contents should not contain corrupt files, malware, viruses, or similar malicious codes that proves fatal to the functioning of the software</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;">&nbsp;</span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Sharing of contents with fellow members:</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Members registered at the app of MegaLive would share and exchange content via the app. The contents of members belong to the ones who have posted the contents and it is preserved in a third party server, which is displayed through the app upon directions by the users.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The users do not have the right to take advantage of another individual's content. The members are not allowed to use the content for commercial purposes or harass fellow members.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Contents of MegaLive:</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Contents, graphical representations, logos, sounds, and similar properties included in MegaLive are owned and protected by copyrights. The entire title, interest, and title would remain intact in our primary database forever. Users need not worry about the personal information being disclosed to third parties.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The members are not allowed to take advantage of the contents by selling or modifying them. Users are not permitted to use the name of the company in keywords or hidden text or Meta tags.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>App restrictions:</strong></em></span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify"><span style="color: #0e101a;"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Users should agree to abide by the laws and regulations of the company. He/she should professionally use the services.</span></span></span></p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
<p style="text-align: justify;" align="justify">&nbsp;</p>
